"""Generate implementation plans for stabilized tasks using Codex CLI."""

import logging
import subprocess
import os
from pathlib import Path

from github_ops import comment_on_issue, add_label, remove_label

log = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPO = os.getenv("GITHUB_REPO", "Anoop-Kondepudi/hackai")


def _handle_plan_failure(issue_number: str, reason: str):
    """Post a failure comment on the issue and revert labels from planning → draft."""
    comment_body = f"## Plan Generation Failed\n\n{reason}\n\nThe task has been reverted to `draft` status for retry.\n\n---\n*Auto-generated by HackAI pipeline*"
    comment_on_issue(issue_number, comment_body)
    remove_label(issue_number, "planning")
    add_label(issue_number, "draft")
    print(f"  [plan] Failure posted to #{issue_number}, reverted to draft")


def _get_repo_tree() -> str:
    """Get a compact file tree of the repo for context."""
    result = subprocess.run(
        ["git", "ls-tree", "-r", "--name-only", "HEAD"],
        capture_output=True, text=True, cwd=PROJECT_ROOT,
    )
    if result.returncode == 0:
        return result.stdout.strip()
    return ""


def _build_prompt(title: str, description: str, label: str, source: str) -> str:
    """Build the prompt for plan generation."""
    repo_tree = _get_repo_tree()

    return f"""You are a senior software engineer reviewing a GitHub issue in the repo {REPO}.

## Issue
**Title:** {title}
**Label:** {label}
**Description:** {description}
**Source (from meeting):** {source}

## Repository Structure
```
{repo_tree}
```

## Your Task

Write a concrete implementation plan for this issue. This plan will be posted as a comment on the GitHub issue and later used by an AI coding agent to implement the changes.

IMPORTANT: The target application is the demo todo app located in the `demo/` folder:
- Frontend: `demo/frontend/` (React + Vite + Tailwind CSS)
- Backend: `demo/backend/` (Express + TypeScript)
- Do NOT modify files in `dashboard/`, `backend/`, `pipeline/`, or any other top-level folder.
- Only modify files under `demo/`.

Requirements:
- Identify the specific files under `demo/` that need to be modified or created
- Describe the exact changes needed in each file
- Note any edge cases or potential issues
- Keep it actionable — another engineer (or AI) should be able to implement this without asking questions
- If this issue is too vague or not actually actionable, say so clearly

Format your response as clean markdown suitable for a GitHub issue comment. Start with a brief summary, then list the implementation steps."""


def generate_plan(title: str, description: str, label: str, source: str,
                  issue_number: str, dry_run: bool = False) -> str | None:
    """Generate an implementation plan using Codex CLI.

    Returns the plan text on success, None on failure.
    """
    prompt = _build_prompt(title, description, label, source)

    print(f"  [plan] Generating plan for #{issue_number}: {title}")

    try:
        result = subprocess.run(
            [
                "codex", "exec",
                "-m", "gpt-5.4",
                "-c", "model_reasoning_effort=\"xhigh\"",
                "--skip-git-repo-check",
                prompt,
            ],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
            timeout=300,
        )

        if result.returncode != 0:
            log.error(f"Codex exec failed for #{issue_number}: {result.stderr}")
            print(f"  [plan] Codex exec failed: {result.stderr[:200]}")
            return None

        plan = result.stdout.strip()
        if not plan:
            log.error(f"Codex returned empty plan for #{issue_number}")
            print(f"  [plan] Empty plan returned")
            return None

        print(f"  [plan] Plan generated ({len(plan)} chars)")

        # Post to GitHub
        if not dry_run:
            comment_body = f"## Implementation Plan\n\n{plan}\n\n---\n*Auto-generated by HackAI pipeline using GPT-5.4 (xhigh reasoning)*"
            success = comment_on_issue(issue_number, comment_body)
            if success:
                print(f"  [plan] Posted plan to #{issue_number}")
                # Update labels: remove planning, add planned
                remove_label(issue_number, "planning")
                add_label(issue_number, "planned")
                print(f"  [plan] Labels updated: planning → planned")
            else:
                print(f"  [plan] Failed to post comment on #{issue_number}")
                return None
        else:
            print(f"  [plan] [dry-run] Would post plan to #{issue_number}")

        return plan

    except subprocess.TimeoutExpired:
        log.error(f"Codex exec timed out for #{issue_number}")
        print(f"  [plan] Timed out after 300s")
        if not dry_run:
            _handle_plan_failure(issue_number, "Plan generation timed out after 300 seconds.")
        return None
    except FileNotFoundError:
        log.error("codex CLI not found — is it installed?")
        print(f"  [plan] codex CLI not found")
        if not dry_run:
            _handle_plan_failure(issue_number, "Codex CLI not found — is it installed?")
        return None
    except Exception as e:
        log.error(f"Plan generation failed for #{issue_number}: {e}")
        print(f"  [plan] Error: {e}")
        if not dry_run:
            _handle_plan_failure(issue_number, f"Plan generation failed: {e}")
        return None
