"""Phase 3: Sanity check plans and create PRs via Codex CLI."""

import logging
import subprocess
import os
import shutil
from pathlib import Path

from github_ops import comment_on_issue, close_issue, add_label, remove_label, create_pr

log = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPO = os.getenv("GITHUB_REPO", "Anoop-Kondepudi/hackai")

CODEX_TIMEOUT = 300  # 5 minutes


# ---------------------------------------------------------------------------
# Sanity check (Phase 3.1)
# ---------------------------------------------------------------------------

def _build_sanity_prompt(plan: str, title: str, description: str) -> str:
    """Build the prompt for the sanity check."""
    return f"""You are evaluating whether a GitHub issue's implementation plan is actionable.

## Issue
**Title:** {title}
**Description:** {description}

## Implementation Plan
{plan}

## Your Task

Look at the codebase and the plan above. Determine if this plan is concretely implementable:
- Does the plan identify real files and real changes?
- Is the issue actually relevant to this codebase?
- Is the plan specific enough to implement (not just "this is out of scope" or "not actionable")?

If the plan IS implementable, respond with exactly:
ACTIONABLE

If the plan is NOT implementable (the plan itself says it's not actionable, the issue is out of scope, too vague, or refers to things not in this codebase), respond with exactly:
NOT_ACTIONABLE: <one paragraph explaining why>

Respond with ONLY one of the above. No other text."""


def sanity_check(plan: str, title: str, description: str,
                 issue_number: str, dry_run: bool = False) -> bool:
    """Run a sanity check on the plan via Codex. Returns True if actionable."""
    prompt = _build_sanity_prompt(plan, title, description)

    print(f"  [sanity] Checking plan for #{issue_number}: {title}")

    try:
        result = subprocess.run(
            [
                "codex", "exec",
                "-m", "gpt-5.4",
                "-c", "model_reasoning_effort=\"xhigh\"",
                "--skip-git-repo-check",
                prompt,
            ],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
            timeout=CODEX_TIMEOUT,
        )

        output = result.stdout.strip()

        if result.returncode != 0 or not output:
            log.error(f"Sanity check failed for #{issue_number}: {result.stderr}")
            print(f"  [sanity] Codex exec failed: {result.stderr[:200]}")
            # Treat codex failure as actionable — don't block on infra issues
            return True

        if output.startswith("NOT_ACTIONABLE:"):
            reason = output[len("NOT_ACTIONABLE:"):].strip()
            print(f"  [sanity] NOT ACTIONABLE: {reason[:100]}...")

            if not dry_run:
                comment_body = (
                    f"## Sanity Check Failed\n\n"
                    f"{reason}\n\n"
                    f"This issue has been closed as not actionable.\n\n"
                    f"---\n*Auto-generated by HackAI pipeline*"
                )
                comment_on_issue(issue_number, comment_body)
                close_issue(issue_number)
                print(f"  [sanity] Issue #{issue_number} closed as not actionable")
            else:
                print(f"  [sanity] [dry-run] Would close #{issue_number} as not actionable")

            return False

        print(f"  [sanity] Plan is actionable for #{issue_number}")
        return True

    except subprocess.TimeoutExpired:
        log.error(f"Sanity check timed out for #{issue_number}")
        print(f"  [sanity] Timed out after {CODEX_TIMEOUT}s — treating as actionable")
        return True
    except FileNotFoundError:
        log.error("codex CLI not found for sanity check")
        print(f"  [sanity] codex CLI not found — treating as actionable")
        return True
    except Exception as e:
        log.error(f"Sanity check error for #{issue_number}: {e}")
        print(f"  [sanity] Error: {e} — treating as actionable")
        return True


# ---------------------------------------------------------------------------
# Implementation + PR (Phase 3.2)
# ---------------------------------------------------------------------------

def _build_implement_prompt(plan: str, title: str, description: str, label: str) -> str:
    """Build the prompt for code implementation."""
    return f"""You are an AI coding agent implementing a GitHub issue.

## Issue
**Title:** {title}
**Label:** {label}
**Description:** {description}

## Implementation Plan
{plan}

## Your Task

Implement the changes described in the plan above. Make the actual code changes to the files in this repository.

Rules:
- Follow the plan closely — implement exactly what it describes
- Write clean, production-quality code
- Do not modify files that the plan does not mention
- Do not add unnecessary comments, docstrings, or type annotations beyond what's needed
- If the plan mentions creating new files, create them
- If the plan mentions modifying existing files, modify them
- Keep changes minimal and focused"""


def _handle_pr_failure(issue_number: str, reason: str):
    """Post a failure comment on the issue and revert labels."""
    comment_body = (
        f"## Implementation Failed\n\n"
        f"{reason}\n\n"
        f"The task has been reverted to `planned` status.\n\n"
        f"---\n*Auto-generated by HackAI pipeline*"
    )
    comment_on_issue(issue_number, comment_body)
    remove_label(issue_number, "implementing")
    add_label(issue_number, "planned")
    print(f"  [pr] Failure posted to #{issue_number}, reverted to planned")


def _run_git(args: list[str], cwd: Path) -> tuple[int, str, str]:
    """Run a git command and return (exit_code, stdout, stderr)."""
    result = subprocess.run(
        ["git"] + args,
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def implement_and_pr(plan: str, task_id: int, title: str, description: str,
                     label: str, issue_number: str,
                     dry_run: bool = False) -> str | None:
    """Implement changes via Codex and create a PR. Returns PR URL or None."""
    branch_name = f"hackai-TASK-{task_id}"
    worktree_path = PROJECT_ROOT.parent / f"hackai-worktree-TASK-{task_id}"

    print(f"  [pr] Starting implementation for #{issue_number}: {title}")

    if dry_run:
        print(f"  [pr] [dry-run] Would create branch {branch_name} and implement changes")
        return "dry-run"

    try:
        # 1. Create worktree with new branch
        code, _, stderr = _run_git(
            ["worktree", "add", str(worktree_path), "-b", branch_name],
            cwd=PROJECT_ROOT,
        )
        if code != 0:
            log.error(f"Failed to create worktree: {stderr}")
            print(f"  [pr] Failed to create worktree: {stderr[:200]}")
            _handle_pr_failure(issue_number, f"Failed to create git worktree: {stderr}")
            return None

        print(f"  [pr] Created worktree at {worktree_path}")

        # 2. Run Codex to implement changes
        prompt = _build_implement_prompt(plan, title, description, label)

        try:
            result = subprocess.run(
                [
                    "codex", "exec",
                    "-m", "gpt-5.4",
                    "-c", "model_reasoning_effort=\"xhigh\"",
                    "--skip-git-repo-check",
                    prompt,
                ],
                capture_output=True,
                text=True,
                cwd=worktree_path,
                timeout=CODEX_TIMEOUT,
            )
        except subprocess.TimeoutExpired:
            log.error(f"Codex implementation timed out for #{issue_number}")
            print(f"  [pr] Codex timed out after {CODEX_TIMEOUT}s")
            _handle_pr_failure(issue_number, f"Code implementation timed out after {CODEX_TIMEOUT} seconds.")
            return None

        if result.returncode != 0:
            log.error(f"Codex implementation failed for #{issue_number}: {result.stderr}")
            print(f"  [pr] Codex failed: {result.stderr[:200]}")
            _handle_pr_failure(issue_number, f"Codex implementation failed: {result.stderr[:500]}")
            return None

        # 3. Check if there are actual changes
        code, diff_output, _ = _run_git(["diff", "--stat"], cwd=worktree_path)
        code2, status_output, _ = _run_git(["status", "--porcelain"], cwd=worktree_path)

        if not diff_output and not status_output:
            print(f"  [pr] No changes made by Codex")
            _handle_pr_failure(issue_number, "Codex ran but made no code changes.")
            return None

        print(f"  [pr] Changes detected:\n{diff_output or status_output}")

        # 4. Stage and commit
        _run_git(["add", "-A"], cwd=worktree_path)
        commit_msg = f"Implement TASK-{task_id}: {title}\n\nCloses #{issue_number}\n\nAuto-generated by HackAI pipeline via Codex GPT-5.4"
        code, _, stderr = _run_git(["commit", "-m", commit_msg], cwd=worktree_path)
        if code != 0:
            log.error(f"Git commit failed: {stderr}")
            print(f"  [pr] Commit failed: {stderr[:200]}")
            _handle_pr_failure(issue_number, f"Git commit failed: {stderr}")
            return None

        print(f"  [pr] Committed changes on {branch_name}")

        # 5. Push branch
        code, _, stderr = _run_git(
            ["push", "-u", "origin", branch_name],
            cwd=worktree_path,
        )
        if code != 0:
            log.error(f"Git push failed: {stderr}")
            print(f"  [pr] Push failed: {stderr[:200]}")
            _handle_pr_failure(issue_number, f"Git push failed: {stderr}")
            return None

        print(f"  [pr] Pushed branch {branch_name}")

        # 6. Create PR
        pr_body = (
            f"Closes #{issue_number}\n\n"
            f"## Implementation\n\n"
            f"Auto-generated implementation for: **{title}**\n\n"
            f"See the [implementation plan](https://github.com/{REPO}/issues/{issue_number}) "
            f"for details.\n\n"
            f"---\n*Auto-generated by HackAI pipeline via Codex GPT-5.4*"
        )
        pr_url = create_pr(
            branch=branch_name,
            title=f"TASK-{task_id}: {title}",
            body=pr_body,
        )

        if not pr_url:
            print(f"  [pr] Failed to create PR")
            _handle_pr_failure(issue_number, "PR creation via gh CLI failed.")
            return None

        print(f"  [pr] Created PR: {pr_url}")

        # 7. Post comment on the issue linking to the PR
        comment_body = (
            f"## PR Created\n\n"
            f"Implementation PR: {pr_url}\n\n"
            f"---\n*Auto-generated by HackAI pipeline*"
        )
        comment_on_issue(issue_number, comment_body)

        # 8. Update labels
        remove_label(issue_number, "implementing")
        add_label(issue_number, "pr-open")
        print(f"  [pr] Labels updated: implementing → pr-open")

        return pr_url

    except Exception as e:
        log.error(f"Implementation failed for #{issue_number}: {e}")
        print(f"  [pr] Error: {e}")
        _handle_pr_failure(issue_number, f"Implementation failed: {e}")
        return None

    finally:
        # Clean up worktree
        if worktree_path.exists():
            try:
                _run_git(["worktree", "remove", str(worktree_path), "--force"], cwd=PROJECT_ROOT)
                print(f"  [pr] Cleaned up worktree")
            except Exception:
                # Fallback: just delete the directory
                shutil.rmtree(worktree_path, ignore_errors=True)
